---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  pre_tasks:
    - name: "Prepare Prometheus requirements"
      become: true
      raw: sudo useradd --no-create-home node_exporter
      changed_when: false
  roles:
    - configure-prometheus-node-exporter
