---
- name: "create backend directory"
  file:
    path: ~/backend
    state: directory
- name: "uncompress zipped backend on remote"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend
- name: "Executing backend"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start